/**
 * Application-wide constants and enumerations.
 *
 * These values are the single source of truth shared by models, migrations,
 * validators and services. Never duplicate a literal status string elsewhere.
 */

const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

const PRODUCT_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

/**
 * Allowed order status transitions.
 * Guards the lifecycle so an order can never jump to an invalid state.
 */
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PAID, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAID]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_DELIVERY]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.CANCELLED]: []
};

/** Statuses an order may no longer be modified from. */
const ORDER_TERMINAL_STATUSES = [ORDER_STATUS.COMPLETED, ORDER_STATUS.CANCELLED];

/** Statuses that still allow the customer to cancel their own order. */
const ORDER_USER_CANCELLABLE_STATUSES = [ORDER_STATUS.PENDING];

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  ABANDONED: 'ABANDONED',
  REVERSED: 'REVERSED'
};

const PAYMENT_PROVIDER = {
  PAYSTACK: 'PAYSTACK'
};

const REVIEW_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  HIDDEN: 'HIDDEN'
};

const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

const NOTIFICATION_CHANNEL = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  PUSH: 'PUSH'
};

/**
 * Notification types. Each type maps to a delivery policy in
 * services/notification.service.js (channels + email template).
 */
const NOTIFICATION_TYPE = {
  // Account
  WELCOME: 'WELCOME',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  EMAIL_VERIFIED: 'EMAIL_VERIFIED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  LOGIN_ALERT: 'LOGIN_ALERT',
  NEW_USER_REGISTERED: 'NEW_USER_REGISTERED',

  // Orders
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_OUT_FOR_DELIVERY: 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  NEW_ORDER: 'NEW_ORDER',

  // Payments
  PAYMENT_SUCCESSFUL: 'PAYMENT_SUCCESSFUL',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  // Catalogue
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_LOW_STOCK: 'PRODUCT_LOW_STOCK',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',

  // Reviews
  NEW_REVIEW: 'NEW_REVIEW',

  // Coupons / promotions
  COUPON_ASSIGNED: 'COUPON_ASSIGNED',

  // Support
  NEW_SUPPORT_TICKET: 'NEW_SUPPORT_TICKET',
  NEW_SUPPORT_MESSAGE: 'NEW_SUPPORT_MESSAGE',
  SUPPORT_REPLY: 'SUPPORT_REPLY',
  SUPPORT_TICKET_STATUS_CHANGED: 'SUPPORT_TICKET_STATUS_CHANGED'
};

const RESOURCE_TYPE = {
  USER: 'USER',
  ORDER: 'ORDER',
  PRODUCT: 'PRODUCT',
  TRANSACTION: 'TRANSACTION',
  REVIEW: 'REVIEW',
  SUPPORT_TICKET: 'SUPPORT_TICKET'
};

/** Image mime types accepted for product/category uploads. */
const ALLOWED_IMAGE_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/avif'
];

module.exports = {
  ROLES,
  PRODUCT_STATUS,
  ORDER_STATUS,
  ORDER_STATUS_TRANSITIONS,
  ORDER_TERMINAL_STATUSES,
  ORDER_USER_CANCELLABLE_STATUSES,
  PAYMENT_STATUS,
  TRANSACTION_STATUS,
  PAYMENT_PROVIDER,
  REVIEW_STATUS,
  TICKET_STATUS,
  TICKET_PRIORITY,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_TYPE,
  RESOURCE_TYPE,
  ALLOWED_IMAGE_MIME_TYPES,

  // Convenience arrays for Sequelize ENUM definitions / Joi validation
  ROLE_VALUES: Object.values(ROLES),
  PRODUCT_STATUS_VALUES: Object.values(PRODUCT_STATUS),
  ORDER_STATUS_VALUES: Object.values(ORDER_STATUS),
  PAYMENT_STATUS_VALUES: Object.values(PAYMENT_STATUS),
  TRANSACTION_STATUS_VALUES: Object.values(TRANSACTION_STATUS),
  PAYMENT_PROVIDER_VALUES: Object.values(PAYMENT_PROVIDER),
  REVIEW_STATUS_VALUES: Object.values(REVIEW_STATUS),
  TICKET_STATUS_VALUES: Object.values(TICKET_STATUS),
  TICKET_PRIORITY_VALUES: Object.values(TICKET_PRIORITY),
  NOTIFICATION_CHANNEL_VALUES: Object.values(NOTIFICATION_CHANNEL),
  NOTIFICATION_TYPE_VALUES: Object.values(NOTIFICATION_TYPE),
  RESOURCE_TYPE_VALUES: Object.values(RESOURCE_TYPE)
};
